### PR TITLE
Two fixes with format_sra

### PR DESCRIPTION
**Pull request by juliema**
on line 63 fixed an error in calculating file size when there are two
input files. This was affecting the number of shards the program would
produce if the same file was given as two input or one input file.

The second fix is allowing format_sra to be able to read input files
that have an _1 in the name rather than a /1 at the end of the name.
This has been checked for both 1 input file as well as for two
different input files.

### CODE REVIEW

**Comment by juliema** [comment]
@daisieh have you had a chance to look these over?

**Comment by daisieh** [comment]
Sorry, no, I'll try to get to it soon.

**Comment by daisieh** [comment]
There are problems with these fixes: I fixed the fixes in #162. Please check the fixes there and merge that PR into this branch. When you do that, then I can merge this PR into master.

**Comment by juliema** [comment]
Ok I made a tiny change.  See what you think @daisieh and we can merge with master.

**Pull request merged**
