### PR TITLE
Adding Abyss.pm file

### PR DESCRIPTION
**Pull request by juliema**
Rough code for getting Abyss.pm merged. Currently it has code for running both the single end and paired end option need to make a flag for user to indicate which one. User has  to indicate a kmer value.

### CODE REVIEW

**Comment by daisieh** [comment]
@juliema, I'm not sure I understand why you're using the single-end option...aren't aTRAM libraries paired-end by default?

**Comment by juliema** [comment]
Hey Daisie,

We found issues with using abyss and paired end option for lice and we
found it worked a lot fast and better if we did not use that option.
However, using abyss with bird libraries the paired end option worked a lot
better.

I think part of the issue is that abyss is designed for whole genome
de-novo assemblies and we are assembling a tiny locus (particularly for
lice) so it is strange for this program.

I think the best way to implement abyss with  aTRAM would be to allow the
user to have both paired-end and single end options, and have a disclaimer
that if the locus they are assembling is small in length the single end
option will assemble faster and easier.


On Mon, Apr 27, 2015 at 6:19 PM, Daisie Huang <notifications@github.com>
wrote:

> @juliema <https://github.com/juliema>, I'm not sure I understand why
> you're using the single-end option...aren't aTRAM libraries paired-end by
> default?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliema/aTRAM/pull/151#issuecomment-96848638>.
>



-- 
Julie Allen
Postdoctoral Researcher
Illinois Natural History Survey
University of Illinois
www.juliamallen.com

**Comment by daisieh** [comment]
I'm having crazy weird problems validating Abyss with aTRAM: I get a lot of weird crashes that I don't quite understand. I don't know if I feel comfortable including it as a default assembler for aTRAM...what do you think?

**Comment by juliema** [comment]
is this with the test_all.pl script?  I think if we can get it to work it
would be really good to have it.

On Mon, Apr 27, 2015 at 8:22 PM, Daisie Huang <notifications@github.com>
wrote:

> I'm having crazy weird problems validating Abyss with aTRAM: I get a lot
> of weird crashes that I don't quite understand. I don't know if I feel
> comfortable including it as a default assembler for aTRAM...what do you
> think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliema/aTRAM/pull/151#issuecomment-96870196>.
>



-- 
Julie Allen
Postdoctoral Researcher
Illinois Natural History Survey
University of Illinois
www.juliamallen.com

**Comment by daisieh** [comment]
It definitely fails with the test fasta files, but I am trying to create a reliable test that works for all cases, and even in this case (some poplar sequences, a matK bait), it crashes erratically. I'm going to ask them about it, but it seems unreliable right now.

**Comment by daisieh** [comment]
I had a quick summit with @sjackman at the Moz Science Sprint today, and I think it works now. Can you try it yourself and see if it's better?

**Comment by daisieh** [comment]
We just did some crazy rebasing things, but a manual inspection suggests everything is in order. @juliema, can you verify that this behaves as expected?

@sjackman recommends the following way to reconcile your git branches:
```
git checkout abyss
git fetch origin
git reset --soft origin/abyss
```
Then run `git diff` and see if there are any changes that you still want to commit.

**Pull request merged**
